version: "3.3"
services:
  db:
    image: mysql:latest
    container_name: rest_db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9907:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

